model_list:
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: gpt-3.5-turbo
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-4
    litellm_params:
      model: gpt-4
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-4-turbo-preview
    litellm_params:
      model: gpt-4-turbo-preview
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-4-0314
    litellm_params:
      model: gpt-4-0314
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-3.5-turbo-0301
    litellm_params:
      model: gpt-3.5-turbo-0301
      api_key: os.environ/OPENAI_API_KEY
  - model_name: gpt-3.5-turbo-16k
    litellm_params:
      model: gpt-3.5-turbo-16k
      api_key: os.environ/OPENAI_API_KEY
  # Anthropic
  - model_name: claude-3-5-sonnet-20240620
    litellm_params:
      model: claude-3-5-sonnet-20240620
      api_key: "os.environ/ANTHROPIC_API_KEY"
  - model_name: claude-3-opus-20240229
    litellm_params:
      model: claude-3-opus-20240229
      api_key: "os.environ/ANTHROPIC_API_KEY"
  - model_name: claude-3-sonnet-20240229
    litellm_params:
      model: claude-3-sonnet-20240229
      api_key: "os.environ/ANTHROPIC_API_KEY"
  - model_name: claude-3-haiku-20240307
    litellm_params:
      model: claude-3-haiku-20240307
      api_key: "os.environ/ANTHROPIC_API_KEY"
  - model_name: claude-2
    litellm_params:
      model: claude-2
      api_key: "os.environ/ANTHROPIC_API_KEY"
  - model_name: claude-2.0
    litellm_params:
      model: claude-2
      api_key: "os.environ/ANTHROPIC_API_KEY"
litellm_settings:
  drop_params: True
  otel: True
  set_verbose: True
  cache: True
  cache_params:
    type: "redis"
    host: os.environ/REDIS_HOST
    port: os.environ/REDIS_PORT
    password: os.environ/REDIS_PASSWORD
  # success_callback: ["traceloop"]
  callbacks: ["otel"]
